### ISSUE TITLE
Occasional errors calling .Expanded() method on swagger with multiple relative file references

### ISSUE THREAD

**Issue by MartinDelVecchio** [go-openapi/loads#11]
I am seeing occasional errors in calling the .Expanded() method on a swagger that has multiple references to external files.

This method always seems to work when there is only one external file reference in my swagger.  But a swagger with multiple external references often causes errors.

I say "often" because it does not fail every time.  The failures seem dependent on the order in which the swagger properties are processed, thanks to Go's insistence on randomizing the order of map iteration.

I have written a simple test program (expand.go in the attached archive) that loops 100 times, doing two things:

- Calls loads.Spec() to load the swagger file
- Calls that document's .Expanded() method to expand/resolve the document.

The document in question is several directories deep, and it has two external file references, to ''../../../../shared/definitions/page.yaml' and ''../../../../shared/something.yaml'.  Those files are in the attached archive in the correct locations.

The .Expanded() method returns an error between 10% and 15% of the time.  The error is always the same:

**Error expanding 'swagger/1/2/3/4/swagger.yaml' (attempt #12):  open \shared\definitions\page.yaml: The system cannot find the path specified.**

Note that the path included in the error message is incorrect.  The file it is trying to open, "\shared\definitions\page.yaml", does not exist.  But that is not the file it should be opening.

It appears that the relative-path calculation has a bug in it.  

[bug.tar.gz](https://github.com/go-openapi/loads/files/1153668/bug.tar.gz)

**Comment by MartinDelVecchio** [comment]
Here is a typical output from a run of this test program:

    C:\temp\bug>go run expand.go
    Error expanding 'swagger/1/2/3/4/swagger.yaml' (attempt #12):  open \shared\definitions\page.yaml: The system cannot find the path specified.
    Error expanding 'swagger/1/2/3/4/swagger.yaml' (attempt #23):  open \shared\definitions\page.yaml: The system cannot find the path specified.
    Error expanding 'swagger/1/2/3/4/swagger.yaml' (attempt #28):  open \shared\definitions\page.yaml: The system cannot find the path specified.
    Error expanding 'swagger/1/2/3/4/swagger.yaml' (attempt #33):  open \shared\definitions\page.yaml: The system cannot find the path specified.
    Error expanding 'swagger/1/2/3/4/swagger.yaml' (attempt #34):  open \shared\definitions\page.yaml: The system cannot find the path specified.
    Error expanding 'swagger/1/2/3/4/swagger.yaml' (attempt #36):  open \shared\definitions\page.yaml: The system cannot find the path specified.
    Error expanding 'swagger/1/2/3/4/swagger.yaml' (attempt #44):  open \shared\definitions\page.yaml: The system cannot find the path specified.
    Error expanding 'swagger/1/2/3/4/swagger.yaml' (attempt #45):  open \shared\definitions\page.yaml: The system cannot find the path specified.
    Error expanding 'swagger/1/2/3/4/swagger.yaml' (attempt #53):  open \shared\definitions\page.yaml: The system cannot find the path specified.
    Error expanding 'swagger/1/2/3/4/swagger.yaml' (attempt #67):  open \shared\definitions\page.yaml: The system cannot find the path specified.
    Error expanding 'swagger/1/2/3/4/swagger.yaml' (attempt #82):  open \shared\definitions\page.yaml: The system cannot find the path specified.
    Error expanding 'swagger/1/2/3/4/swagger.yaml' (attempt #84):  open \shared\definitions\page.yaml: The system cannot find the path specified.
    Error expanding 'swagger/1/2/3/4/swagger.yaml' (attempt #88):  open \shared\definitions\page.yaml: The system cannot find the path specified.
    Error expanding 'swagger/1/2/3/4/swagger.yaml' (attempt #91):  open \shared\definitions\page.yaml: The system cannot find the path specified.
    Error expanding 'swagger/1/2/3/4/swagger.yaml' (attempt #93):  open \shared\definitions\page.yaml: The system cannot find the path specified.
    Error expanding 'swagger/1/2/3/4/swagger.yaml' (attempt #99):  open \shared\definitions\page.yaml: The system cannot find the path specified.

    84 successes, 16 errors.

**Comment by MartinDelVecchio** [comment]
I set the SWAGGER_DEBUG environment variable to 1, and ran it a few times.  It seems to work when this is the first line of output:

    2017/07/17 15:07:25 normalizing ../../../../shared/definitions/page.yaml#/definitions/Page against swagger\1\2\3\4 (../../../../shared/definitions/page.yaml#/definitions/Page)

And it seems to fail when this is the first line of output:

    2017/07/17 15:10:22 normalizing ../../../../shared/something.yaml#/definitions/Something against swagger\1\2\3\4 (../../../../shared/something.yaml#/definitions/Something)

**Comment by casualjim** [comment]
can you run `swagger flatten` on your spec with relative file reference and then run `swagger generate` ?

**Comment by MartinDelVecchio** [comment]
I don't have a 'swagger' command or utility; how can I build it?

**Comment by casualjim** [comment]
go get -u github.com/go-swagger/go-swagger/cmd/swagger

**Comment by MartinDelVecchio** [comment]
I executed that command.  How can I build the 'swagger' command?

Thanks.

**Comment by casualjim** [comment]
it already built it now, that's what go get does

**Comment by MartinDelVecchio** [comment]
It might be built, but I can't find it to execute it.  I tried in Windows and in Cygwin.

What does that command do?  Does it modify the swagger file?  Can the same thing be done in the go-openapi API?

Thanks.

**Comment by casualjim** [comment]
the go get command installs the binary in $GOPATH/bin (%GOPATH%\bin) which for a correctly functioning go development environment should be setup in your PATH environment variable.

**Comment by MartinDelVecchio** [comment]
I executed the following command:

    swagger flatten swagger\1\2\3\4\swagger.yaml >swagger\1\2\3\4\flattened.yaml

Then changed my expand.go test program to open the new flattened.yaml instead of the original swagger.yaml.  The test now passes 100 of 100 times, every time.

It looks like the "swagger flatten" command is loading the swagger via loads.Spec(), then calling analysis.Flatten() on it.  It looks like the specDoc is modified in place.  

So it seems to me that adding a call to analysis.Flatten() should solve my probem.  But it doesn't appear to; when I change my loop to this:

      // Load it
      specDoc, err := loads.Spec (swaggerFile)
      if err != nil {
         fmt.Printf ("Error loading '%s' (attempt #%d):  %v\n", swaggerFile, i, err)
         errorCount += 1
         continue
      }

      // Flatten it
      err = analysis.Flatten (analysis.FlattenOpts{
   		BasePath: specDoc.SpecFilePath(),
		   Spec:     analysis.New(specDoc.Spec()),
   	})
      if err != nil {
         fmt.Printf ("Error flattening '%s' (attempt #%d):  %v\n", swaggerFile, i, err)
         errorCount += 1
         continue
      }

      // Expand it
      _, err = specDoc.Expanded()
      if err != nil {
         fmt.Printf ("Error expanding '%s' (attempt #%d):  %v\n", swaggerFile, i, err)
         errorCount += 1
      } else {
         successCount += 1
      }

I still get occasional errors on the call to .Expanded().  The calls to analysis.Flatten() succeed.

What am I missing here?

Thanks.

**Comment by casualjim** [comment]
you're creating a copy for the analysis.Flatten

try this
```go
flatSpec := analysis.New(specDoc.Spec())
err = analysis.Flatten (analysis.FlattenOpts{
	BasePath: specDoc.SpecFilePath(),
	   Spec:     flatSpec,
})
if err != nil {
     fmt.Printf ("Error flattening '%s' (attempt #%d):  %v\n", swaggerFile, i, err)
     errorCount += 1
     continue
  }

  // Expand it
  _, err = flatSpec.Expanded()
  if err != nil {
     fmt.Printf ("Error expanding '%s' (attempt #%d):  %v\n", swaggerFile, i, err)
     errorCount += 1
  } else {
     successCount += 1
  }
```

**Comment by MartinDelVecchio** [comment]
Here is my current loop:

      // Load it
      specDoc, err := loads.Spec (swaggerFile)
      if err != nil {
         fmt.Printf ("Error loading '%s' (attempt #%d):  %v\n", swaggerFile, i, err)
         errorCount += 1
         continue
      }

      // Flatten it
      flatSpec := analysis.New(specDoc.Spec())
      err = analysis.Flatten (analysis.FlattenOpts{
	      BasePath: specDoc.SpecFilePath(),
	      Spec:     flatSpec,
      })      
      if err != nil {
         fmt.Printf ("Error flattening '%s' (attempt #%d):  %v\n", swaggerFile, i, err)
         errorCount += 1
         continue
      }

      // Expand it
      _, err = flatSpec.Expanded()
      if err != nil {
         fmt.Printf ("Error expanding '%s' (attempt #%d):  %v\n", swaggerFile, i, err)
         errorCount += 1
      } else {
         successCount += 1
      }

This won't compile:

    .\expand.go:38: flatSpec.Expanded undefined (type *analysis.Spec has no field or method Expanded)

**Comment by MartinDelVecchio** [comment]
So I got it to work by writing the flattened spec back out to a temp file, then reading it in again:

      // Load it
      specDoc, err := loads.Spec (swaggerFile)
      if err != nil {
         fmt.Printf ("Error loading '%s' (attempt #%d):  %v\n", swaggerFile, i, err)
         errorCount += 1
         continue
      }

      // Flatten it
      err = analysis.Flatten(analysis.FlattenOpts{
         BasePath: specDoc.SpecFilePath(),
         Spec:     analysis.New(specDoc.Spec()),
      })
      if err != nil {
         fmt.Printf ("Error flattening '%s' (attempt #%d):  %v\n", swaggerFile, i, err)
         errorCount += 1
         continue
      }

      // Write the flattened spec to a temporary file
      b, err := json.MarshalIndent (specDoc.Spec(), "", "  ")
      if err != nil {
         fmt.Printf ("Error marshaling '%s' (attempt #%d):  %v\n", swaggerFile, i, err)
         errorCount += 1
         continue
      }
      err = ioutil.WriteFile (tempFile, b, 0x644)
      if err != nil {
         fmt.Printf ("Error writing temp file for '%s' (attempt #%d):  %v\n", swaggerFile, i, err)
         errorCount += 1
         continue
      }

      // Read that file back in
      newDoc, err := loads.Spec (tempFile)
      if err != nil {
         fmt.Printf ("Error reloading temp file for '%s' (attempt #%d):  %v\n", swaggerFile, i, err)
         errorCount += 1
         continue
      }

      // Expand it
      _, err = newDoc.Expanded()
      if err != nil {
         fmt.Printf ("Error expanding '%s' (attempt #%d):  %v\n", swaggerFile, i, err)
         errorCount += 1
      } else {
         successCount += 1
      }

And this worked 100% of the time.  I then went to apply this logic to my production code, and it fails 100% of the time.  I get this error:

    Failed to expand path /add: Failed to expand POST operation: Failed to expand parameter 1: Failed to load ../../config/system/system.yaml#/definitions/ServiceError: open ../../config/system/system.yaml: no such file or directory

Why is it trying to resolve an external link in a flattened document?  Because it is not, apparently flattened:

          {
            "type": "string",
            "name": "level",
            "in": "query",
            "schema": {
              "required": [],
              "$ref": "../../config/system/system.yaml#/definitions/ServiceError"
            }

I then took my test code and pointed it at our production YAML, and got the exact same error.

So it appears that, for some reason, I cannot use the flatten workaround.  That brings us back to the bug in the .Expanded() method, wherein it fails to calculate the correct path forthe second external reference, but only in a certain order.

Do you have enough information to investigate that bug?

Thanks.

**Comment by casualjim** [comment]
this should also work, but without the round trip to disk

```go
analysis.Flatten(
	analysis.FlattenOpts{
		Spec:     analysis.New(specDoc.Spec()),
		BasePath: specDoc.BasePath(),
	},
)
spec.ExpandSpec(specDoc.Spec(), &spec.ExpandOptions{
	RelativeBase: filepath.Dir(specDoc.SpecFilePath()),
})
````

**Comment by MartinDelVecchio** [comment]
I can't get this form to work at all, even with my test Swagger:

      // Load it
      specDoc, err := loads.Spec (swaggerFile)
      if err != nil {
         fmt.Printf ("Error loading '%s' (attempt #%d):  %v\n", swaggerFile, i, err)
         errorCount += 1
         continue
      }

      // Flatten it
      err = analysis.Flatten(
         analysis.FlattenOpts{
            Spec:     analysis.New(specDoc.Spec()),
            BasePath: specDoc.BasePath(),
         },
      )
      if err != nil {
         fmt.Printf ("Error flattening '%s' (attempt #%d):  %v\n", swaggerFile, i, err)
         errorCount += 1
         continue
      }

      // Expand it
      err = spec.ExpandSpec(specDoc.Spec(), &spec.ExpandOptions{
         RelativeBase: filepath.Dir(specDoc.SpecFilePath()),
      })
      if err != nil {
         fmt.Printf ("Error expanding '%s' (attempt #%d):  %v\n", swaggerFile, i, err)
         errorCount += 1
         continue
      } else {
         successCount += 1
      }

It fails every time:

    Error flattening 'swagger/1/2/3/4/swagger.yaml' (attempt #0):  open ../../../../shared/something.yaml: no such file or directory
    Error flattening 'swagger/1/2/3/4/swagger.yaml' (attempt #1):  open ../../../../shared/definitions/page.yaml: no such file or directory

Etc.  I tried several different paths as the RelativeBase, but always get the same failure.

**Comment by MartinDelVecchio** [comment]
Is there an update on this issue?  It continues to plague us.

Thanks.

**Comment by MartinDelVecchio** [comment]
I have been looking into another instance of what appears to be the same problem, with a bit more data.

In this case, the expansion fails even though the reference and the definition are in the same YAML file.  The problem occurs because the expander gets confused about which file it should be looking at.

I am attaching bug2.tar.gz, which contains the simplest files I can create to demonstrate this problem.

In this example, there are three YAML files:

1) ./m/s/s/a/a.yaml, which contains a reference to '../../../../s/a.yaml#/definitions/DataObject'

2) ./s/a.yaml, which contains the definition for DataObject.  It has two properties:  one is a local reference to '#/definitions/StrEnum', and the other is an external reference to './e.yaml#/definitions/EObject'.

3) ./s/e.yaml, which contains the definition for EObject

Again, I believe that this expansion succeeds sometimes and fails sometimes because of the random iteration of Go map keys.  Specifically, the expansion succeeds with it is asked to resolve the local reference first, and fails when it is asked to resolve the external reference first.

The debug logs indicate that when it resolves the external reference first, it remembers that file (./s/e.yaml), and tries to use it to resolve the local reference.  But that external file does not contain the local reference, and it fails.

I believe that the solution might have something to do with calling resolver.reset() at the right place, but I haven't been able to figure out where that might be.

Can you please take a look at this code and see if you can see the problem?

Thank you.

[bug2.tar.gz](https://github.com/go-openapi/loads/files/1268190/bug2.tar.gz)

**Comment by casualjim** [comment]
We are looking into resolving refs better

**Comment by MartinDelVecchio** [comment]
Thank you.

**Comment by MartinDelVecchio** [comment]
My boss told me to either fix this bug or rip the code out of our product.  So I tried again.

I stumbled upon a change that appears to make the expansion succeed 100% of the time.  I say stumbled because the code in question isn't well-commented, and I can't really figure out what it is doing.

But I noticed that this code in the schemaLoader.resolveRef() method was producing the error (line #421 in expander.go):

...
data, _, _, err := r.load(currentRef.GetURL())
	if err != nil {
		return err
	}
...

When this fails, currentRef isn't the correct path it should be looking for, but ref is.  So I added a second try, on ref, in the failure case:

...
	data, _, _, err := r.load(currentRef.GetURL())
	if err != nil {
		data, _, _, err = r.load(ref.GetURL())
		if err != nil {
			return err
		}
	}
...

And it seems to work every time.

I am not sure why this appears to fix it.  And I am not sure if this code should be looking at currentRef at all.

What do you think?

Thanks.

**Comment by kreamyx** [comment]
@MartinDelVecchio There is a recent PR in go-openapi/spec that resolved this issue. Please let me know if you are still facing problems after you update your go-openapi/spec repo
