### ISSUE TITLE
Are some deps in go.mod unused? running go mod tidy gets rid of a bunch

### ISSUE THREAD

**Issue by kennyjpowers** [go-openapi/loads#23]
After running
`go mod tidy`

the go.mod file becomes:

module github.com/go-openapi/loads

require (
	github.com/go-openapi/analysis v0.0.0-20180825180245-b006789cd277
	github.com/go-openapi/spec v0.17.0
	github.com/go-openapi/strfmt v0.17.0 // indirect
	github.com/go-openapi/swag v0.17.0
	github.com/stretchr/testify v1.2.2
	gopkg.in/yaml.v2 v2.2.1
)

**Comment by fredbi** [comment]
deps have been updated and go mod tidy applied. No more relevant
