### ISSUE TITLE
summary missing

### ISSUE THREAD

**Issue by phamdt** [go-openapi/loads#24]
unless i'm overlooking it, there doesn't appear to be the "summary" attribute when loading the open api doc. am i missing something?

**Comment by fredbi** [comment]
@phamdt 

`summary` is an attribute of operations as per [Swagger 2.0](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#operation-object) and is supported by our [data model](https://github.com/go-openapi/spec/blob/8557d72e4f077c2dbe1e48df09e596b6fb9b7991/operation.go#L44).

Could you please describe where exactly you are adding a `summary` attribute that wouldn't be supported? Thanks.

**Comment by fredbi** [comment]
Evidence:
```go
import (
	"testing"

	"github.com/stretchr/testify/require"
)

func TestIssue24(t *testing.T) {
	d, err := Analyzed(PetStoreJSONMessage, "")
	require.NoError(t, err)
	require.NotNil(t, d)

	for pth, ops := range d.Analyzer.Operations() {
		for id, op := range ops {
			summary := op.Summary
			t.Logf("summary for [%s][%s]: %s", pth, id, summary)
		}
	}
}
```
```bash
go test -v -run Issue24
=== RUN   TestIssue24
    issue24_test.go:17: summary for [GET][/pets/{id}]: Finds the pet by id
    issue24_test.go:17: summary for [GET][/pets]: Finds all pets in the system
    issue24_test.go:17: summary for [DELETE][/pets/{id}]: 
    issue24_test.go:17: summary for [POST][/pets]: Creates a new pet
--- PASS: TestIssue24 (0.03s)
PASS
ok  	github.com/go-openapi/loads	0.037s
```
