### ISSUE TITLE
`spec.PathLoader` incorrectly set during initialization

### ISSUE THREAD

**Issue by a2800276** [go-openapi/loads#29]
During setup in the module's `init` function, the `spec.PathLoader` function is set to the  `DocLoader` function of the loader being added to the loader chain. Because the final loader to be added is the YAML loader, this is _always_ the `swag.YamlDoc` function which causes problems for subsequent uses of the `spec` package.

E.g. when loading and subsequently validating a json document, the validation will use the incorrectly set YamlDoc function to load `$ref`s and the call will fail because of errors caused by attempts to unmarshal  json data using a yaml decoder.

The fix I'm providing sets the PathLoader after determining the proper format during loading (see issue: https://github.com/go-openapi/loads/issues/28). I can think of two complications with this approach, but I think  it's the best that can be done without major refactoring:

- Scenario: load schema1.json, load schema2.yaml, then validate schema1.json ... This uses the incorrect Pathloader that resulted from loading a yaml file before validating the json file. This is a result of Pathloader being global and can't really be fixed without major refactoring
- load schema1.json which references an external schema (see footnote) which is yaml. Can't really be fixed because Pathloader doesn't take the loaded schema's mime-type into account. Again requires major rework

## Steps to reproduce

I've attaching a [json schema](https://github.com/go-openapi/loads/files/5542109/pathLoaderIssue.json.txt). Loading and subsequent validation causes an error concerning invalid yaml. 

## Footnote

-  there is _another_ bug hidden (inside of `the spec module` I guess) : The reference that is being resolved in the test case is _local_ to the file and therefor already loaded. So there's no need to actually reload it! This seems to be an issue with the caching mechanism and would also presumably require major effort to debug and fix.

- document matcher uses the the file extension to determine yaml vs. json. This can be misleading for a number of reasons: files without extension (if remotely retrieved, mime-type could be used), files with no mime-type or incorrect extensions, in which case heuristics or brute force is necessary, ...

**Comment by fredbi** [comment]
fixed by #30
