### ISSUE TITLE
Does this package support loading an OpenAPI 3.0 specification document?

### ISSUE THREAD

**Issue by jondavidi** [go-openapi/loads#32]
I currently use a swagger 2.0 `spec.json` file to validate http response bodies using `loads.Spec()` and then passing that to a swagger proxy which does the validation in tests.

I converted the swagger 2.0 spec file into a compliant OpenAPI 3.0 YAML file, but when I pass to the new file, it parses but does not seem to actually enforce the specification, such as required parameters, that were caught when I passed the original swagger 2.0 specification. 

Upon further investigation in debug, it appears the spec document that is generated from `loads.Spec()` has swagger 2.0 schema metadata, so I'm thinking it's parsing the spec file but interpreting it as swagger 2.0 and not actually doing anything with it since it's in OAS 3.0

So my question is, does the package support loading OpenAPI 3.0 Specification? It was hard to find any documentation confirming or denying this. And if so, should it work with passing a OAS 3.0 YAML document?

I'm encountering this issue in `v0.19.7`

Thanks!

**Comment by fredbi** [comment]
@jondavidi no this package only supports OpenAPI (swagger) 2.0.
There have been some developments around 3.0, though (github.com/go-openapi/spec3), but there are far for being complete.

The whole go-openapi suite of libraries and code generator (go-swagger) only supports 2.0.

**Comment by jondavidi** [comment]
@fredbi thanks for the clarification and quick response!
