### ISSUE TITLE
JSONDoc issue loading json file without having .json extension

### ISSUE THREAD

**Issue by Zero-Prime** [go-openapi/loads#8]
wrote json to url, but did not load and received 404 error.  Needed to add .json to the path to be able to grab the file.  Shouldn't this actually load the content types?

**Comment by casualjim** [comment]
could you elaborate a little bit on what doesn't work?
You're saying it wouldn't load the json document from  a http url if it didn't have the json extension?
Were you able to curl the url and see the spec?

**Comment by Zero-Prime** [comment]
Yes I ran the curl request and it did not load with application/json in the header.  I was hitting the URL ../v2/_optimus/schema and it did not work.  In the code needed to add .json

**Comment by casualjim** [comment]
I still don't understand what you're trying to serve? How you're serving and so on. The loads package doesn't care about extensions or even headers.

**Comment by fredbi** [comment]
Invalid bug report
